/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package cartas;

import java.awt.Color;
import java.awt.Dimension;
import java.io.IOException;
import static java.lang.Thread.sleep;
import java.util.ArrayList;
import java.util.Collections;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.accessibility.AccessibleContext;
import javax.accessibility.AccessibleStateSet;
import javax.imageio.ImageIO;
import javax.swing.Icon;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import javax.swing.JToggleButton;

/**
 *
 * @author usuario
 */
public class Cartas extends javax.swing.JFrame {

    /**
     * Creates new form Ejercicio14
     */
    //controlamos los botones que tenemos activos
    static int activeButtons = 0;
    static int  hits = 0;
    ArrayList<JToggleButton> allButtons= new ArrayList<JToggleButton>();
       
   

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jButtonShowCards = new javax.swing.JButton();
        jButtonChangeOrder = new javax.swing.JButton();
        jToggleButton4 = new javax.swing.JToggleButton();
        jToggleButton1 = new javax.swing.JToggleButton();
        jToggleButton2 = new javax.swing.JToggleButton();
        jToggleButton3 = new javax.swing.JToggleButton();
        jToggleButton8 = new javax.swing.JToggleButton();
        jToggleButton5 = new javax.swing.JToggleButton();
        jToggleButton6 = new javax.swing.JToggleButton();
        jToggleButton7 = new javax.swing.JToggleButton();
        statusButtonsLabel = new javax.swing.JLabel();
        jLabelCountSeletecButtons = new javax.swing.JLabel();
        jLabelBG = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBounds(new java.awt.Rectangle(0, 0, 0, 0));
        setResizable(false);
        setSize(new java.awt.Dimension(663, 470));
        setType(java.awt.Window.Type.POPUP);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setLayout(null);

        jButtonShowCards.setBackground(new java.awt.Color(255, 255, 255));
        jButtonShowCards.setText("Mostrar cartas");
        jButtonShowCards.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonShowCardsActionPerformed(evt);
            }
        });
        jPanel1.add(jButtonShowCards);
        jButtonShowCards.setBounds(430, 30, 130, 23);

        jButtonChangeOrder.setBackground(new java.awt.Color(255, 255, 255));
        jButtonChangeOrder.setText("Cambiar orden");
        jButtonChangeOrder.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonChangeOrderActionPerformed(evt);
            }
        });
        jPanel1.add(jButtonChangeOrder);
        jButtonChangeOrder.setBounds(610, 30, 140, 23);

        jToggleButton4.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jToggleButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jToggleButton4ActionPerformed(evt);
            }
        });
        jPanel1.add(jToggleButton4);
        jToggleButton4.setBounds(770, 90, 133, 163);

        jToggleButton1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jToggleButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jToggleButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jToggleButton1);
        jToggleButton1.setBounds(290, 90, 133, 163);

        jToggleButton2.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jToggleButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jToggleButton2ActionPerformed(evt);
            }
        });
        jPanel1.add(jToggleButton2);
        jToggleButton2.setBounds(450, 90, 133, 163);

        jToggleButton3.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jToggleButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jToggleButton3ActionPerformed(evt);
            }
        });
        jPanel1.add(jToggleButton3);
        jToggleButton3.setBounds(610, 90, 133, 163);

        jToggleButton8.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jToggleButton8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jToggleButton8ActionPerformed(evt);
            }
        });
        jPanel1.add(jToggleButton8);
        jToggleButton8.setBounds(770, 290, 133, 163);

        jToggleButton5.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jToggleButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jToggleButton5ActionPerformed(evt);
            }
        });
        jPanel1.add(jToggleButton5);
        jToggleButton5.setBounds(450, 290, 133, 163);

        jToggleButton6.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jToggleButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jToggleButton6ActionPerformed(evt);
            }
        });
        jPanel1.add(jToggleButton6);
        jToggleButton6.setBounds(290, 290, 133, 163);

        jToggleButton7.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jToggleButton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jToggleButton7ActionPerformed(evt);
            }
        });
        jPanel1.add(jToggleButton7);
        jToggleButton7.setBounds(610, 290, 133, 163);

        statusButtonsLabel.setForeground(new java.awt.Color(255, 255, 255));
        jPanel1.add(statusButtonsLabel);
        statusButtonsLabel.setBounds(640, 480, 20, 20);

        jLabelCountSeletecButtons.setForeground(new java.awt.Color(255, 255, 255));
        jLabelCountSeletecButtons.setText("Botones activos");
        jPanel1.add(jLabelCountSeletecButtons);
        jLabelCountSeletecButtons.setBounds(540, 480, 90, 20);

        jLabelBG.setIcon(new javax.swing.ImageIcon(getClass().getResource("/bg/bgFrame.jpg"))); // NOI18N
        jPanel1.add(jLabelBG);
        jLabelBG.setBounds(0, -100, 1200, 710);

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1150, 510));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jToggleButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jToggleButton1ActionPerformed
            JToggleButton btn = (JToggleButton) evt.getSource(); 
          
            if (btn.isSelected()) { 
                activeButtons++;
                jToggleButton1.setIcon(new ImageIcon("bgCartas/carta-1.png"));
                
                comprobarVerde();
                comprobar();
                statusButtonsLabel.setText(String.valueOf(activeButtons));
            } else { 
               jToggleButton1.setIcon(null);
                activeButtons=0;
           
                btn.setBackground(Color.lightGray);
                statusButtonsLabel.setText(String.valueOf(activeButtons));
            } 
    }//GEN-LAST:event_jToggleButton1ActionPerformed

    private void jToggleButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jToggleButton3ActionPerformed
        JToggleButton btn = (JToggleButton) evt.getSource(); 
        
        
        if (btn.isSelected()) { 
                activeButtons++;
                //btn.setText("active");
           
                jToggleButton3.setIcon(new ImageIcon("bgCartas/carta-1.png"));
                comprobarVerde();
                comprobar();
                statusButtonsLabel.setText(String.valueOf(activeButtons));
            } else { 
               // btn.setText("non active");
                activeButtons=0;
               jToggleButton3.setIcon(null);
                btn.setBackground(Color.lightGray);
                statusButtonsLabel.setText(String.valueOf(activeButtons));
            } 
        
    }//GEN-LAST:event_jToggleButton3ActionPerformed

    private void jToggleButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jToggleButton2ActionPerformed
        JToggleButton btn = (JToggleButton) evt.getSource(); 
     
        
        if (btn.isSelected()) { 
                activeButtons++;
               
                jToggleButton2.setIcon(new ImageIcon("bgCartas/carta-2.png"));
                
                comprobarRojo();
                comprobar();
                
                statusButtonsLabel.setText(String.valueOf(activeButtons));
            } else { 
                jToggleButton2.setIcon(null);
                activeButtons=0;
                
                btn.setBackground(Color.lightGray);
                statusButtonsLabel.setText(String.valueOf(activeButtons));
            } 
        
    }//GEN-LAST:event_jToggleButton2ActionPerformed

    private void jToggleButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jToggleButton4ActionPerformed
        JToggleButton btn = (JToggleButton) evt.getSource(); 
       
        
        if (btn.isSelected()) { 
                activeButtons++;
              
               jToggleButton4.setIcon(new ImageIcon("bgCartas/carta-2.png"));
                comprobarRojo();
                comprobar();
                statusButtonsLabel.setText(String.valueOf(activeButtons));
        } else { 
            
               jToggleButton4.setIcon(null);
                activeButtons=0;
                System.out.println(String.valueOf(activeButtons));
                
                btn.setBackground(Color.lightGray);
                statusButtonsLabel.setText(String.valueOf(activeButtons));
            } 
    }//GEN-LAST:event_jToggleButton4ActionPerformed

    private void jToggleButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jToggleButton5ActionPerformed
      JToggleButton btn = (JToggleButton) evt.getSource(); 
        
        
        if (btn.isSelected()) { 
                activeButtons++;
                jToggleButton5.setIcon(new ImageIcon("bgCartas/carta-3.png"));
                
                comprobarAzul();
                comprobar();
                statusButtonsLabel.setText(String.valueOf(activeButtons));
            } else { 
                jToggleButton5.setIcon(null);
                activeButtons=0;
                
                btn.setBackground(Color.lightGray);
                statusButtonsLabel.setText(String.valueOf(activeButtons));
            } 
    }//GEN-LAST:event_jToggleButton5ActionPerformed

    private void jToggleButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jToggleButton6ActionPerformed
        JToggleButton btn = (JToggleButton) evt.getSource(); 
      
        
        if (btn.isSelected()) { 
                activeButtons++;
                jToggleButton6.setIcon(new ImageIcon("bgCartas/carta-3.png"));
                comprobarAzul();
                comprobar();
                statusButtonsLabel.setText(String.valueOf(activeButtons));
            } else { 
                jToggleButton6.setIcon(null);
                activeButtons=0;
                
                btn.setBackground(Color.lightGray);
                statusButtonsLabel.setText(String.valueOf(activeButtons));
            } 
    }//GEN-LAST:event_jToggleButton6ActionPerformed

    private void jToggleButton7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jToggleButton7ActionPerformed
        JToggleButton btn = (JToggleButton) evt.getSource(); 
        
        
        if (btn.isSelected()) { 
                activeButtons++;
               jToggleButton7.setIcon(new ImageIcon("bgCartas/carta-4.png"));
                
                
                comprobarAmarillo();
                comprobar();
                statusButtonsLabel.setText(String.valueOf(activeButtons));
            } else { 
                jToggleButton7.setIcon(null);
                activeButtons=0;
                
                btn.setBackground(Color.lightGray);
                statusButtonsLabel.setText(String.valueOf(activeButtons));
            }
    }//GEN-LAST:event_jToggleButton7ActionPerformed

    private void jToggleButton8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jToggleButton8ActionPerformed
        JToggleButton btn = (JToggleButton) evt.getSource(); 
        if (btn.isSelected()) { 
                activeButtons++;
                jToggleButton8.setIcon(new ImageIcon("bgCartas/carta-4.png"));
                comprobarAmarillo();
                comprobar();
                statusButtonsLabel.setText(String.valueOf(activeButtons));
            } else { 
               jToggleButton8.setIcon(null);
                activeButtons=0;
               
                btn.setBackground(Color.lightGray);
                statusButtonsLabel.setText(String.valueOf(activeButtons));
            }
    }//GEN-LAST:event_jToggleButton8ActionPerformed

    private void jButtonChangeOrderActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonChangeOrderActionPerformed
       randomPosition();
    }//GEN-LAST:event_jButtonChangeOrderActionPerformed

    private void jButtonShowCardsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonShowCardsActionPerformed
        showCards();
    }//GEN-LAST:event_jButtonShowCardsActionPerformed
    
    public void comprobarVerde(){
        if(jToggleButton1.isSelected()&&jToggleButton3.isSelected()){
            System.out.println("ha acertado el verde");
            //JOptionPane.showMessageDialog(null, "ha acertado");
            jToggleButton1.setEnabled(false);
            jToggleButton3.setEnabled(false);
            activeButtons=0;
            hits++;
            System.out.println(hits);
        }else{
            //System.out.println("encuentra su pareja");
            jToggleButton1.setEnabled(true);
            jToggleButton3.setEnabled(true);
        }
    }
    public void comprobarRojo(){
        if(jToggleButton2.isSelected()&&jToggleButton4.isSelected()){
            System.out.println("ha acertado el rojo");
            //JOptionPane.showMessageDialog(null, "ha acertado");
            jToggleButton2.setEnabled(false);
            jToggleButton4.setEnabled(false);
            activeButtons=0;
             hits++;
             System.out.println(hits);
        }else{
            jToggleButton2.setEnabled(true);
            jToggleButton4.setEnabled(true);
           // System.out.println("encuentra su pareja");
        }
    }
    public void comprobarAzul(){
        if(jToggleButton5.isSelected()&&jToggleButton6.isSelected()){
            System.out.println("ha acertado el azul");
            //JOptionPane.showMessageDialog(null, "ha acertado");
            jToggleButton5.setEnabled(false);
            jToggleButton6.setEnabled(false);
            activeButtons=0;
             hits++;
             System.out.println(hits);
        }else{
            jToggleButton5.setEnabled(true);
            jToggleButton6.setEnabled(true);
            //System.out.println("encuentra su pareja");
        }
    }
     public void comprobarAmarillo(){
        if(jToggleButton7.isSelected()&&jToggleButton8.isSelected()){
            System.out.println("ha acertado el amarillo");
            //JOptionPane.showMessageDialog(null, "ha acertado");
            jToggleButton7.setEnabled(false);
            jToggleButton8.setEnabled(false);
            activeButtons=0;
            hits++;
            System.out.println(hits);
        }else{
            jToggleButton7.setEnabled(true);
            jToggleButton8.setEnabled(true);
            //System.out.println("encuentra su pareja");
        }
    }

   
    public void comprobar(){
        boolean rojo  = jToggleButton2.isSelected()&&jToggleButton4.isSelected();
        boolean verde = jToggleButton1.isSelected()&&jToggleButton3.isSelected();
        boolean azul  = jToggleButton5.isSelected()&&jToggleButton6.isSelected();
        boolean amarillo = jToggleButton7.isSelected()&&jToggleButton8.isSelected();
        
        if(activeButtons == 2  ){
            
            if (verde || rojo || azul || amarillo ){
                // JOptionPane.showMessageDialog(null, "ha acertado");
                  System.out.println();
                  System.out.println("Ha encontrado un pareja");
                  
            }
            
            else{
                this.activeButtons = 0;
                
                JOptionPane.showMessageDialog(null, "vuelva a intentarlo");
                
                jToggleButton1.setIcon(null);
                jToggleButton2.setIcon(null);
                jToggleButton3.setIcon(null);
                jToggleButton4.setIcon(null);
                jToggleButton5.setIcon(null);
                jToggleButton6.setIcon(null);
                jToggleButton7.setIcon(null);
                jToggleButton8.setIcon(null);
                
                jToggleButton1.setBackground(Color.lightGray);
                jToggleButton1.setSelected(false);
                jToggleButton3.setBackground(Color.lightGray);
                jToggleButton3.setSelected(false);
                
                jToggleButton7.setBackground(Color.lightGray);
                jToggleButton7.setSelected(false);
                jToggleButton8.setBackground(Color.lightGray);
                jToggleButton8.setSelected(false);
                
                jToggleButton5.setBackground(Color.lightGray);
                jToggleButton5.setSelected(false);
                jToggleButton6.setBackground(Color.lightGray);
                jToggleButton6.setSelected(false);
                
                
                jToggleButton2.setBackground(Color.lightGray);
                jToggleButton2.setSelected(false);
                jToggleButton4.setBackground(Color.lightGray);
                jToggleButton4.setSelected(false);
            
            }
        }
        //TODO Resetear el juego
        else if (hits == 4){
                System.out.println("Enhorabuena ha ganado!!!");
                JOptionPane.showMessageDialog(null, "Enhorabuena ha ganado!!!");
                resetGame();
        }
       /* else if (verde && rojo && azul && amarillo){
                System.out.println("Enhorabuena ha ganado!!!");
                JOptionPane.showMessageDialog(null, "Enhorabuena ha ganado!!!");
        }*/else {
           // activeButtons=0;
        }
        
    }
    
    public void resetGame(){
                hits=0;
                jToggleButton1.setIcon(null);
                jToggleButton2.setIcon(null);
                jToggleButton3.setIcon(null);
                jToggleButton4.setIcon(null);
                jToggleButton5.setIcon(null);
                jToggleButton6.setIcon(null);
                jToggleButton7.setIcon(null);
                jToggleButton8.setIcon(null);
                
                jToggleButton1.setEnabled(true);
                jToggleButton2.setEnabled(true);
                jToggleButton3.setEnabled(true);
                jToggleButton4.setEnabled(true);
                jToggleButton5.setEnabled(true);
                jToggleButton6.setEnabled(true);
                jToggleButton7.setEnabled(true);
                jToggleButton8.setEnabled(true);
                
                jToggleButton1.setBackground(Color.lightGray);
                jToggleButton1.setSelected(false);
                jToggleButton3.setBackground(Color.lightGray);
                jToggleButton3.setSelected(false);
                
                jToggleButton7.setBackground(Color.lightGray);
                jToggleButton7.setSelected(false);
                jToggleButton8.setBackground(Color.lightGray);
                jToggleButton8.setSelected(false);
                
                jToggleButton5.setBackground(Color.lightGray);
                jToggleButton5.setSelected(false);
                jToggleButton6.setBackground(Color.lightGray);
                jToggleButton6.setSelected(false);
                
                
                jToggleButton2.setBackground(Color.lightGray);
                jToggleButton2.setSelected(false);
                jToggleButton4.setBackground(Color.lightGray);
                jToggleButton4.setSelected(false);
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Cartas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Cartas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Cartas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Cartas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Cartas().setVisible(true);
            }
        });
        
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonChangeOrder;
    private javax.swing.JButton jButtonShowCards;
    private javax.swing.JLabel jLabelBG;
    private javax.swing.JLabel jLabelCountSeletecButtons;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JToggleButton jToggleButton1;
    private javax.swing.JToggleButton jToggleButton2;
    private javax.swing.JToggleButton jToggleButton3;
    private javax.swing.JToggleButton jToggleButton4;
    private javax.swing.JToggleButton jToggleButton5;
    private javax.swing.JToggleButton jToggleButton6;
    private javax.swing.JToggleButton jToggleButton7;
    private javax.swing.JToggleButton jToggleButton8;
    private javax.swing.JLabel statusButtonsLabel;
    // End of variables declaration//GEN-END:variables
 public Cartas() {
        super("Encuentra las parejas de cartas");
       // this.setIconImage(new Image("bgCartas/carta-1.png"));
        //setIcon(new ImageIcon("bgCartas/carta-1.png"));
        // this.setUndecorated(true) ; 
        initComponents();
        this.setLocationRelativeTo(null);
        //statusButtonsLabel.disable();
        
        this.setIconImage(new ImageIcon(getClass().getResource("../bg/logo.png")).getImage());
        
       // jLabel1.disable();
        allButtons.add(jToggleButton1);
        allButtons.add(jToggleButton2);
        allButtons.add(jToggleButton3);
        allButtons.add(jToggleButton4);
        allButtons.add(jToggleButton5);
        allButtons.add(jToggleButton6);
        allButtons.add(jToggleButton7);
        allButtons.add(jToggleButton8);
        /*
        allButtons.get(0).setBackground(Color.yellow);
        allButtons.get(1).setBackground(Color.green);
        allButtons.get(2).setBackground(Color.blue);
        allButtons.get(3).setBackground(Color.red);
        allButtons.get(4).setBackground(Color.BLACK);
        allButtons.get(5).setBackground(Color.ORANGE);
        allButtons.get(6).setBackground(Color.CYAN);
        allButtons.get(7).setBackground(Color.MAGENTA);*/
        //this.revalidate();
        //this.pack();
       Thread hilo = new Thread(){
            public synchronized void run(){
                try {
                	
                	
                       
                        jToggleButton1.setIcon(new ImageIcon("bgCartas/carta-1.png"));
                        sleep(30);
                        jToggleButton2.setIcon(new ImageIcon("bgCartas/carta-2.png"));
                        sleep(30);
                        jToggleButton3.setIcon(new ImageIcon("bgCartas/carta-1.png"));
                        sleep(30);
                        jToggleButton4.setIcon(new ImageIcon("bgCartas/carta-2.png"));
                        sleep(30);
                        jToggleButton5.setIcon(new ImageIcon("bgCartas/carta-3.png"));
                        sleep(30);
                        jToggleButton6.setIcon(new ImageIcon("bgCartas/carta-3.png"));
                        sleep(30);
                        jToggleButton7.setIcon(new ImageIcon("bgCartas/carta-4.png"));
                        sleep(30);
                        jToggleButton8.setIcon(new ImageIcon("bgCartas/carta-4.png"));
                        sleep(30);
                        sleep(1500);
                        
                        for(int i=0;i<allButtons.size();i++){
                                System.out.println("ocultamos cartas");
                		allButtons.get(i).setIcon(null);
                                sleep(30);
                	}
                } catch (InterruptedException ex) {
                    ex.printStackTrace();
                }
            }
	};
        hilo.start();
        
    }
    private void showCards() {
        Thread hilo = new Thread(){
            public synchronized void run(){
                try {
                	
                	
                       
                        jToggleButton1.setIcon(new ImageIcon("bgCartas/carta-1.png"));
                        sleep(30);
                        jToggleButton2.setIcon(new ImageIcon("bgCartas/carta-2.png"));
                        sleep(30);
                        jToggleButton3.setIcon(new ImageIcon("bgCartas/carta-1.png"));
                        sleep(30);
                        jToggleButton4.setIcon(new ImageIcon("bgCartas/carta-2.png"));
                        sleep(30);
                        jToggleButton5.setIcon(new ImageIcon("bgCartas/carta-3.png"));
                        sleep(30);
                        jToggleButton6.setIcon(new ImageIcon("bgCartas/carta-3.png"));
                        sleep(30);
                        jToggleButton7.setIcon(new ImageIcon("bgCartas/carta-4.png"));
                        sleep(30);
                        jToggleButton8.setIcon(new ImageIcon("bgCartas/carta-4.png"));
                        sleep(30);
                        sleep(1500);
                        
                        for(int i=0;i<allButtons.size();i++){
                                System.out.println("ocultamos cartas");
                		allButtons.get(i).setIcon(null);
                                sleep(30);
                	}
                } catch (InterruptedException ex) {
                    ex.printStackTrace();
                }
            }
	};
        hilo.start();
    }
    private void randomPosition() {
        resetGame();
        @SuppressWarnings("unchecked")
        ArrayList<JToggleButton> copyAllButtons =  (ArrayList<JToggleButton>) allButtons.clone();//new ArrayList<JToggleButton>();
     
        
        System.err.println("------------------------------------------");      
        //System.out.println("clonebu " +cloneAllButtons.get(i).getBounds() );
        System.out.println("Original ArrayList:"+allButtons);
        System.out.println("Cloned ArrayList:"+copyAllButtons);
        
        
        Collections.shuffle(copyAllButtons);            
        Collections.shuffle(allButtons);            
        System.out.println("intercambiamos posición");      
        System.out.println("Original ArrayList:"+allButtons);
        System.out.println("Cloned ArrayList:"+copyAllButtons);
        
        /*
        allButtons.get(0).setBounds(cloneAllButtons.get(0).getBounds());  
        System.out.println("original : " +allButtons.get(0).getBounds() );
        System.out.println("copia : " +cloneAllButtons.get(0).getBounds() );
        System.out.println("amarillo");      
        
        System.out.println("verde");      
        allButtons.get(1).setBounds(cloneAllButtons.get(1).getBounds());  
        System.out.println("original : " +allButtons.get(1).getBounds() );
        System.out.println("copia : " +cloneAllButtons.get(1).getBounds() );
        
        System.out.println("azul");      
        allButtons.get(2).setBounds(cloneAllButtons.get(2).getBounds());  
        System.out.println("original : " +allButtons.get(2).getBounds() );
        System.out.println("copia : " +cloneAllButtons.get(2).getBounds() );
        
        System.out.println("red");      
        allButtons.get(3).setBounds(cloneAllButtons.get(3).getBounds());  
        System.out.println("original : " +allButtons.get(3).getBounds() );
        System.out.println("copia : " +cloneAllButtons.get(3).getBounds() );
        */
        allButtons.get(0).setBackground(Color.yellow);
        allButtons.get(1).setBackground(Color.green);
        allButtons.get(2).setBackground(Color.blue);
        allButtons.get(3).setBackground(Color.red);
        allButtons.get(4).setBackground(Color.BLACK);
        allButtons.get(5).setBackground(Color.ORANGE);
        allButtons.get(6).setBackground(Color.CYAN);
        allButtons.get(7).setBackground(Color.MAGENTA);
      
        /*    
        allButtons.get(0).setBounds(copyAllButtons.get(0).getBounds());  
        allButtons.get(1).setBounds(copyAllButtons.get(1).getBounds());  
        allButtons.get(2).setBounds(copyAllButtons.get(2).getBounds());  
        allButtons.get(3).setBounds(copyAllButtons.get(3).getBounds());  
        allButtons.get(4).setBounds(copyAllButtons.get(4).getBounds());  
        allButtons.get(5).setBounds(copyAllButtons.get(5).getBounds());  
        allButtons.get(6).setBounds(copyAllButtons.get(6).getBounds());  
        allButtons.get(7).setBounds(copyAllButtons.get(7).getBounds()); */
         
        //this.revalidate();
       // this.pack();
        //jPanel1.repaint();
       
          
            
        for (int i = 0; i < allButtons.size(); i++) {
            
            allButtons.get(i).setBounds(copyAllButtons.get(i).getBounds());  
            //System.out.println("clonebu " +cloneAllButtons.get(i).getBounds() );
            System.out.println("--------------------");
            System.out.println("copia "+ i +" " +copyAllButtons.get(i).getBounds());
            System.out.println("allbuto "+ i +" " +allButtons.get(i).getBounds());
            allButtons.get(i).repaint();  
               
            //System.out.println("clonebuAFTER " +cloneAllButtons.get(i).getBounds() );
         //   System.out.println("allbutoAFTER" + i +" "+allButtons.get(i).getBounds() );
            
            
        }
       
          
        
    }

   
    
}
